### PR TITLE
feat: update protobuf to 4.21.6

### PR DESCRIPTION
**Pull request by irusland**
Refs: #222

### CODE REVIEW

**Comment by daxartio** [comment]
Обнови эту либу еще types-protobuf = "^3.18.2"

**Comment by irusland** [comment]
Поднял до types-protobuf = "^4.22.0.2"
падает на
poetry run mypy tinkoff examples scripts
tinkoff/invest/grpc/common_pb2.pyi:6: error: Library stubs not installed for "google.protobuf.descriptor" (or incompatible with Python 3.9)
tinkoff/invest/grpc/common_pb2.pyi:6: note: Hint: "python3 -m pip install types-protobuf"
tinkoff/invest/grpc/common_pb2.pyi:6: note: (or run "mypy --install-types" to install all missing stub packages)
tinkoff/invest/grpc/common_pb2.pyi:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
tinkoff/invest/grpc/common_pb2.pyi:6: error: Library stubs not installed for "google.protobuf" (or incompatible with Python 3.9)
tinkoff/invest/grpc/common_pb2.pyi:7: error: Library stubs not installed for "google.protobuf.internal.enum_type_wrapper" (or incompatible with Python 3.9)
tinkoff/invest/grpc/common_pb2.pyi:7: error: Library stubs not installed for "google.protobuf.internal" (or incompatible with Python 3.9)
tinkoff/invest/grpc/common_pb2.pyi:8: error: Library stubs not installed for "google.protobuf.message" (or incompatible with Python 3.9)

**Comment by irusland** [comment]
Поручилось максимум до 3.20.4.6 поднять

**Comment by daxartio** [comment]
> Поручилось максимум до 3.20.4.6 поднять

Попробуй вообще удалить mypy-protobuf

Судя по твоей ошибке, там будто types-protobuf вообще не поставилось

**Review by daxartio — APPROVED** [review]

**Pull request merged**
